version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - VERSION=docker
    volumes:
      - ./config/plex:/config
      - media_tv:/tv
      - media_movies:/movies
      - media_music:/music
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/sonarr:/config
      - media_tv:/tv
      - downloads:/downloads
    ports:
      - "8989:8989"
    depends_on:
      - qbittorrent
      - prowlarr
      - jackett
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/radarr:/config
      - media_movies:/movies
      - downloads:/downloads
    ports:
      - "7878:7878"
    depends_on:
      - qbittorrent
      - prowlarr
      - jackett
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    depends_on:
      - flaresolverr
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - AUTO_UPDATE=true #optional
    volumes:
      - ./config/jackett:/config
      - downloads:/downloads
    ports:
      - "9117:9117"
    depends_on:
      - flaresolverr
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Denver
    ports:
      - "8191:8191"
    restart: unless-stopped

  # OpenVPN client container
  openvpn:
    image: docker.io/dperson/openvpn-client:latest
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Denver
    volumes:
      - ./config/openvpn:/vpn
    ports:
      - "8080:8080"  # qBittorrent web UI
      - "6881:6881"  # qBittorrent torrenting port TCP
      - "6881:6881/udp"  # qBittorrent torrenting port UDP
    security_opt:
      - label:disable
    devices:
      - /dev/net/tun
    restart: unless-stopped
    command: '-f "" -r 192.168.0.0/16'
    networks:
      default:
        aliases:
          - qbittorrent  # Allow other containers to reach qBittorrent via this name

  # qBittorrent bound to OpenVPN
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:openvpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config/qbittorrent:/config
      - downloads:/downloads
    depends_on:
      - openvpn
    restart: unless-stopped


networks:
  default:
    name: media-stack

volumes:
  # Media storage volumes - customize paths in .env file or modify directly
  media_tv:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_ROOT:-/mnt/WD_1T/media}/tv
  
  media_movies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_ROOT:-/mnt/WD_1T/media}/movies
  
  media_music:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_ROOT:-/mnt/WD_1T/media}/music
  
  downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_ROOT:-/mnt/WD_1T/downloads}